### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by AFWL** [h-cwc/wallace-corporation#1]
Any chance you could add a color palette (like what's in this project; https://github.com/sainnhe/gruvbox-material) containing the main colors of the theme to the README?

I am trying to make this my system-wide theme, and a color palette would make the process so much easier.

**Comment by AFWL** [comment]
I should specify, the theme in question is Wallace Corporation.

**Comment by h-cwc** [comment]
Should be doable. But I'm bogged down with work at the moment, so it probably won't be added anytime soon. If you can't wait, you can just have a look at the json file.

**Comment by AFWL** [comment]
I'll get started with the JSON file, if it works out i'd be happy to make PR.
